### PR TITLE
Add Snapshot proposal creation and voting tutorial

### PR DESCRIPTION
**Pull request by octofi**
Hi team,

Just a small token of appreciation for creating snapshot.page and keeping it so simple.

We needed to write a guide for our community to participate in governance, so we have repurposed for use on your docs. Hope you find it useful and thanks again for creating an awesome tool for the community. 

I'm sure you'll be able to see if we've missed anything. 

Best regards 🐙

### CODE REVIEW

**Comment by octofi** [comment]
Just edited the title of PR, noticed I wrote Ass instead of Add -- my apologies! Been a looonng day!

**Comment by octofi** [comment]
Hi @bonustrack, any chance you find this useful? Let me know if you have any feedback. Take care ;-)

**Comment by bonustrack** [comment]
Hey that's awesome thank you @octofi i will review your PR once i get in computer. Sorry for the late reply i didn't seen your PR until now

**Comment by octofi** [comment]
No problem at all @bonustrack, I can see from the PRs flooding in that you've been very busy!

**Review by bonustrack — APPROVED** [review]
Looking good thank you for your contribution!

**Pull request merged**
